version: "3"
services:
  database:
    image: mariadb:10.1
    volumes:
    - 'mariadb_data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: "jeesample"
      MYSQL_USER: "jeeuser"
      MYSQL_PASSWORD: "password"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
volumes:
  mariadb_data:
    driver: local
