version: "3"
services:
  controller:
    build: wlp-controller
    ports: 
    - "9443:9443"
  member:
    build: wlp-member
    depends_on:
    - controller
  webserver:
    build: webserver
    ports: 
    - "80:80"
    - "443:443"
    depends_on:
    - controller
